# basic options
title: My new awesome blog
author: Merih Bozbura
email: merihbozbura@gmail.com
description: What a wonderful blog
github_username: merihbozbura
linkedin_username: merihb


# Build settings
plugins: jemoji
markdown: kramdown
theme: minima
